# Generated by Django 5.2 on 2025-06-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0004_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='style',
            field=models.CharField(choices=[('Professional', 'Professional'), ('Trendy', 'Trendy'), ('Luxury', 'Luxury'), ('Elegant', 'Elegant')], default='Elegant', max_length=50),
        ),
    ]
